#####
name: NiceGAN
bidirect: False #Unidirectional or bidirectional
regist: False
noise_level: 1  #  noise level
port: 6019   #  port parameters
save_root: './output/Nice/NC+R/retrained/'
image_save: './output/Nice/NC+R/img/'

Adv_lamda: 1
Cyc_lamda: 10
Corr_lamda: 20
Smooth_lamda: 10


epoch: 0        # starting epoch
n_epochs: 80       # How often do you want to display output images during training
batchSize: 1              # size of the batches
dataroot: r'C:\Users\NM_RR\Desktop\SJ\data\SPECT_data\rest\'     # root directory of the dataset
val_dataroot: r'C:\Users\NM_RR\Desktop\SJ\data\SPECT_data\rest\'
lr: 0.0001                   # initial learning rate
decay_epoch: 20            # epoch to start linearly decaying the learning rate to 0
size: 256              # size of the data crop
input_nc: 3         
output_nc: 3                  
cuda: True                
n_cpu: 0

